Task#1 create entities
vdrabll/EmployeeManager pull request #1
Opened 2024-08-02 07:27 UTC by vdrabll

2024-08-02 09:05 UTC, DmitryTsybulkin commented on compose.yaml
> +      - 'POSTGRES_USER=vdrabll'
Всем гитхабом угараем над слитыми кредами

2024-08-02 09:07 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +@Setter
А в чём разница между Data, Getter, Setter, AllArgsConstructor, NoArgsConstructor? Читай доки в коде к аннотации Data

2024-08-02 09:09 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
Аналогично - посмотришь изнутри на NoArgsConstructor, и увидишь:
`AccessLevel access() default AccessLevel.PUBLIC;`

2024-08-02 09:10 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
Во-первых, почему AUTO? Во-вторых изучи GeneratedValue внутри.

2024-08-02 09:47 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +    private BigInteger id;
Во-первых, слабо понимаю смысловую нагрузку `nullable = false` и `updatable = false` тут, потому что, из кода ты можешь создать новую запись в бд таким образом (потому что ты указала стратегию генерации значения, значит postgresql сам запишет id):
`insert into some_entity (id, some_field) VALUES (null, 'pisos');`
Если же ты сделаешь это через sql, у тебя всё равно поле помечено как primary key, выпадет исключение:
> ERROR: null value in column "id" of relation "category" violates not-null constraint

Аналогично с update - если ты попытаешься изменить id на существующий, то выпадет:

> ERROR: duplicate key value violates unique constraint "category_pkey"
> [2024-08-02 11:29:02] Detail: Key (id)=(2) already exists.

В то же время, тебе ничто не мешает изменить id на тот, которого ещё нет в таблице. Проверил сейчас, если ты попытаешь даже через java изменить id (через setter), ничего не произойдёт, даже если ты попытаешься создать новую запись через конструктор:
`myRepository.save(new MyEntity(1L, "pisos")); // мы полагаем, что под id=1 уже есть запись`
В таком случае, у тебя просто произойдёт как бы put, то есть просто поменяется второе поле у записи под id=1.

Во-вторых, BigInteger - тебе погоду не испортит, но предпочтительнее юзать Long, потому что он проще, быстрее, занимает меньше памяти. BigInteger актуально использовать, когда тебе не хватает диапазона Long.
Ответ от чатажпт:
> Summary
> - Use Long for primary keys in almost all scenarios due to its sufficient range, better performance, and simplicity.
> -  Use BigInteger only if you have a specific need for extremely large values beyond the range of Long, which is very uncommon.

2024-08-02 09:50 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +    @JoinColumn(name = "id")
Во-первых, БД - пизданётся, потому что у тебя уже есть поле "id", нужно называть более соответствующе, типа "employee_id".
Во-вторых странная связь: в департаменте может быть только 1 работяга в один конкретный момент времени?

2024-08-02 09:51 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Employee.java
> +    private BigInteger id;
Аналогично, смотри департамент за прояснением

2024-08-02 09:56 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Employee.java
> +    @Column(nullable = false)
Особо смысла нет в nullable, потому что по-умолчанию у тебя true ставится. 
> Но, вообще, лучше проверить, что таким образом у тебя точно будет поле по-умолчанию, есть вероятность, что это нужно будет через Column аннотацию указать: https://www.baeldung.com/jpa-default-column-values

2024-08-02 09:56 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Employee.java
> +    @JoinColumn(name = "id")
Аналогично тому, что выше - id уже есть,

2024-08-02 09:58 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Schedule.java
> +    public enum Location {
Вынеси в отдельный файл

2024-08-02 10:00 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
Я устал писать, смотри выше

2024-08-02 10:00 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
> +    public enum Type {
Все енамы - нафиг из класса, всё по отдельным файлам

2024-08-02 10:05 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/repository/DepartmentRepository.java
> +public interface DepartmentRepository extends JpaRepository<BigInteger, Department> {
Лучше ещё пометить аннотацией `org.springframework.stereotype.Repository`

2024-08-02 10:06 UTC, DmitryTsybulkin commented on src/main/resources/application.properties
>  spring.application.name=EmployeeManager
Лучше писать в формате yaml - так сразу показываешь, что ты jun+

2024-08-02 10:09 UTC, DmitryTsybulkin commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://postgresql:5432/db
Это для docker'а у тебя написано, судя по всему, если ты запускаешь проект не в контейнере, а постгрес в докере, у тебя будет что то типа: jdbc:postgresql://localhost:5432/db (потому что докер на локалхосте работает, как и твой проект), если же было в докере - у него там своя сеть есть

2024-08-02 10:10 UTC, DmitryTsybulkin commented on src/main/resources/application.properties
> +spring.datasource.password=422448Vika
Ура, креды, каждому гитхабовцу по кредам. Мб попробовать этот пароль к твоей почте, заработает?

2024-08-02 10:11 UTC, DmitryTsybulkin commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
Я надеюсь, ты прочитала разницу между update,create и тд

2024-08-02 10:11 UTC, DmitryTsybulkin commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +#      - file: db/changelog/changeset/create-employee-table.yaml
ладно

2024-08-02 10:11 UTC, DmitryTsybulkin commented on src/main/resources/liquibase.properties
> +password=422448Vika
ммм ооо креды ммм
![image](https://github.com/user-attachments/assets/fde43e11-d40c-4ac3-b98f-750af1b80657)

2024-08-02 10:13 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/SalaryHistory.java
> +@Entity(name = "salary_history")
необязательно над каждой сущностью писать, как она будет в бд называться. JPA - не тупой, нормально тебе смапит `SalaryHistory` в `salary_history` сам

2024-08-02 10:13 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Project.java
> +    private Set<Employee> users = new HashSet<>();
Ещё момент - почему где то ты юзаешь Set, а где то List, в чём прикол? ну поняли мы, что ты знаешь эти коллекции

2024-08-02 10:15 UTC, DmitryTsybulkin requested changes
Тут был Димас

2024-08-02 10:15 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Employee.java
> +    private List<Schedule> schedule = new ArrayList<>();
Зачем тут нужна инициализация? Про параметры OneToMany тоже читай, у тебя маппинг не правильный.

2024-08-02 12:33 UTC, vdrabll commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +    @JoinColumn(name = "id")
как тогда сделать эту связь хм

2024-08-03 18:05 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
>      @ManyToOne
ManyToMany

2024-08-03 18:38 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Leave.java
>      private Date startDate;
java.sql.Date

2024-08-03 18:39 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
>      @JoinColumn(name = "id")
уже есть id

2024-08-03 18:39 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Schedule.java
>      @JoinColumn(name = "id")
уже есть id

2024-08-13 20:50 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Employee.java
> +    @JoinColumn(name = "position_id")
pizdec

2024-08-13 20:50 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Leave.java
> +    @OneToOne
pizdec

2024-08-13 20:51 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/PositionHistory.java
> +import java.util.Date;
pizdec

2024-08-13 20:52 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Project.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
pizdec: пробелы где

2024-08-13 20:52 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/SalaryHistory.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
pizdec: пробелы где

2024-08-13 20:52 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/PositionHistory.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
pizdec: пробелы где

2024-08-13 20:52 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Position.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
pizdec: пробелы где

2024-08-13 20:52 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Leave.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
pizdec: пробелы где

2024-08-13 20:52 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Employee.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
pizdec: пробелы где

2024-08-13 20:52 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
pizdec: пробелы где

2024-08-13 20:53 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
> +    @JoinColumn(name = "project_id")
pizdec

2024-08-13 20:53 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
> +    private Priority priority; // переделать в енам
pizdec

2024-08-13 20:53 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
> +import java.util.Date;
pizdec

2024-08-13 20:55 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
> +    private Priority priority; // переделать в енам
коммент оставила для будущих поколений?

2024-08-13 20:55 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Task.java
> +    @ManyToMany(mappedBy = "employee_id")
пиздец

2024-08-13 20:58 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +    void creatDepartment(Department department) { }
пиздец      🥾😵‍💫🤬

2024-08-13 21:01 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/EmployeeService.java
> +    void delete(Long id ) { this.repository.deleteById(id);}
пиздец нахуя лишний проблеллэь/юбЬЭэд

2024-08-13 21:01 UTC, DmitryTsybulkin commented on src/main/resources/application.yml
> +  datasource:
👍

2024-08-13 21:02 UTC, DmitryTsybulkin commented on src/main/resources/db/changelog/changesets/v1_initial_shema.sql
> +        id                  long auto_increment primary key,
я в ахуе

2024-08-13 21:03 UTC, DmitryTsybulkin commented on src/main/resources/db/changelog/changesets/v1_initial_shema.sql
> +        id                  long auto_increment primary key,
https://www.postgresql.org/docs/16/datatype-numeric.html#DATATYPE-SERIAL

2024-08-13 21:05 UTC, DmitryTsybulkin commented on src/main/resources/db/changelog/changesets/v1_initial_shema.sql
> +        employee_id          long not null,
https://www.postgresql.org/docs/16/ddl-constraints.html#DDL-CONSTRAINTS-FK

2024-08-13 21:07 UTC, DmitryTsybulkin commented on src/main/resources/db/changelog/changesets/v1_initial_shema.sql
> +        role                ENUM('USER', 'ADMIN')
https://www.postgresql.org/docs/16/datatype-enum.html

2024-08-13 21:08 UTC, DmitryTsybulkin commented on src/main/resources/db/changelog/changesets/v1_initial_shema.sql
> +        salary              decimal not null
https://www.postgresql.org/docs/current/datatype-money.html

2024-08-13 21:09 UTC, DmitryTsybulkin commented on src/main/resources/db/changelog/changesets/v1_initial_shema.sql
> +create table project(
if not exists

2024-08-13 21:10 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/EmployeeService.java
> +    void delete(Long id ) { this.repository.deleteById(id);}
Модификаторы доступа

2024-08-13 21:11 UTC, DmitryTsybulkin requested changes
я в ахуе

2024-08-16 08:43 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +    @Column(updatable = false)
Почему ту здесь это свойство добавила, а на других таблицах нет? в чём прикол?

2024-08-16 08:43 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/entity/Department.java
> +@Data
Так @Data или @Getter @Setter?

2024-08-27 17:57 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +        return departmentRepository.save(department);
нет проверки, что департамент уже есть

2024-08-27 17:58 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +        departmentRepository.delete(department);
а если нет такого депа?

2024-08-27 17:58 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +        if (!allEmployeesFromDepartment.contains(newEmployee)) {
изучи как работает метод contains

2024-08-27 17:58 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +            allEmployeesFromDepartment.remove(employee);
аналогично

2024-08-27 17:59 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/EmployeeService.java
> +    private EmployeeRepository employeeRepository;
думаешь заавтовайриться?

2024-08-27 17:59 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +    private DepartmentRepository departmentRepository;
заавтовайриться?

2024-08-27 17:59 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +@AllArgsConstructor
думаешь?

2024-08-27 17:59 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/DepartmentService.java
> +@Setter
зачем?

2024-08-27 18:00 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/EmployeeService.java
> +        } else { throw new ExecutionException(String.format("Сотрудник с данным email уже зарегестрирован : %s ", newEmployee.getEmail())); }
слишком длинная строка

2024-08-27 18:01 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/EmployeeService.java
> +        employeeById.getTasks().add(task);
а таск существует в бд?

2024-08-27 18:01 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/EmployeeService.java
> +        employeeById.getTasks().add(task);
в чём разница с методом выше?

2024-08-27 18:03 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/LeaveService.java
> +        leaveById.setEndDate(leave.getEndDate());
я буду рофлить, если сюда null прилетит

2024-08-27 18:04 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/LeaveService.java
> +    public List<Leave> getAllInThisMonth(Long employeeId) {
а зачем аргумент?

2024-08-27 18:04 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/LeaveService.java
> +        return leaveRepository.findAllByYear(thisYear);
в чём отличие от метода выше?

2024-08-27 18:06 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/ProjectService.java
> +            new RuntimeException(String.format("Проект уже найден в базе данных")); // TODO: кастомные типы ошибок
рандомные классы для одного и того же типа исключения бросаешь

2024-08-27 18:07 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/ProjectService.java
> +        if (!project.getEmployees().contains(project)) {
чё?

2024-08-27 18:07 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/ProjectService.java
> +            new RuntimeException(String.format("Сотрудник по данному id: %s уже найден в списке участников этого проекта", id)); // TODO: кастомные типы ошибок
сломал шею, пока читал

2024-08-27 18:07 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/ProjectService.java
> +        if (!project.getEmployees().contains(employee)) {
а?

2024-08-27 18:07 UTC, DmitryTsybulkin commented on src/main/java/com/example/EmployeeManager/service/ProjectService.java
> +            new RuntimeException(String.format("Сотрудник по данному id: %s не найден в списке участников этого проекта", id)); // TODO: кастомные типы ошибок
...

2024-08-29 09:00 UTC, merged